# Generated by GitHub Copilot - Aug-27-2026
"""
Render the TicketAudit brand SVG assets to PNG and ICO files.

Run after editing mockups/brand/*.svg:

    python scripts/render_brand.py

It renders:
1. About dialog lockup (gui/assets/ticketaudit-lockup.png)
2. Standalone dark & light lockup PNGs (mockups/brand/renders/)
3. Multi-resolution app icon PNGs (16, 32, 48, 64, 128, 256, 512, 1024)
4. Multi-size Windows .ico files (gui/assets/ticketaudit.ico, mockups/brand/renders/ticketaudit-app.ico)

It prints the SHA-256 of what it wrote for the About dialog artwork. That hash is
the `_lh` literal in gui/app_pyside.py's show_about_dialog, which refuses to
display artwork it cannot verify - so a new render means updating that literal or
the dialog silently shows nothing.
"""
import hashlib
import os
import re
import struct
import sys
from typing import Optional

# Before QGuiApplication: see note on font rendering.
os.environ.pop("QT_QPA_PLATFORM", None)

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, ROOT)

from PySide6.QtCore import QBuffer, QByteArray, QIODevice, QRectF, Qt  # noqa: E402
from PySide6.QtGui import (QColor, QFontDatabase, QGuiApplication,    # noqa: E402
                           QImage, QPainter)
from PySide6.QtSvg import QSvgRenderer                               # noqa: E402

BRAND_DIR = os.path.join(ROOT, "mockups", "brand")
RENDERS_DIR = os.path.join(BRAND_DIR, "renders")
GUI_ASSETS_DIR = os.path.join(ROOT, "gui", "assets")

SOURCE_LIGHT = os.path.join(BRAND_DIR, "ticketaudit-lockup-light.svg")
SOURCE_DARK = os.path.join(BRAND_DIR, "ticketaudit-lockup-dark.svg")
SOURCE_ICON = os.path.join(BRAND_DIR, "ticketaudit-app-icon.svg")

TARGET_DIALOG_LOCKUP = os.path.join(GUI_ASSETS_DIR, "ticketaudit-lockup.png")
TARGET_APP_ICO = os.path.join(GUI_ASSETS_DIR, "ticketaudit.ico")
TARGET_RENDERS_ICO = os.path.join(RENDERS_DIR, "ticketaudit-app.ico")

ICON_SIZES = [16, 32, 48, 64, 128, 256, 512, 1024]
ICO_SIZES = [16, 32, 48, 64, 128, 256]

# Rendered at 3x the ~260px the dialog displays it at, so it stays crisp on high-DPI displays.
RENDER_WIDTH = 780
LOCKUP_FULL_WIDTH = 1600
MARGIN = 6


# Generated by GitHub Copilot - Aug-27-2026
def _resolve_font_stacks(svg: str) -> str:
    """
    Collapse each CSS font stack to the first family actually installed.

    QtSvg does not walk a comma-separated font-family list like browsers do;
    it matches the attribute as a single family name.
    """
    installed = set(QFontDatabase.families())

    def pick(match: re.Match) -> str:
        families = [f.strip().strip("'\"") for f in match.group(1).split(",")]
        for family in families:
            if family in installed:
                return f'font-family="{family}"'
        return match.group(0)

    return re.sub(r'font-family="([^"]+)"', pick, svg)


# Generated by GitHub Copilot - Aug-27-2026
def _render_svg_to_image(svg_content: str, width: int, height: Optional[int] = None) -> QImage:
    """
    Render SVG content to an ARGB32 QImage at the specified dimensions.
    """
    renderer = QSvgRenderer(QByteArray(svg_content.encode("utf-8")))
    if not renderer.isValid():
        raise SystemExit("Qt could not parse SVG content")

    box = renderer.viewBoxF()
    if height is None:
        height = round(width * box.height() / box.width())

    image = QImage(width, height, QImage.Format.Format_ARGB32)
    image.fill(QColor(0, 0, 0, 0))

    painter = QPainter(image)
    painter.setRenderHint(QPainter.RenderHint.Antialiasing, True)
    painter.setRenderHint(QPainter.RenderHint.TextAntialiasing, True)
    painter.setRenderHint(QPainter.RenderHint.SmoothPixmapTransform, True)
    renderer.render(painter, QRectF(0, 0, width, height))
    painter.end()
    return image


# Generated by GitHub Copilot - Aug-27-2026
def _crop_to_content(image: QImage, margin: int = MARGIN) -> QImage:
    """
    Trim fully transparent outer margins from a rendered image.
    """
    left, top = image.width(), image.height()
    right = bottom = -1
    for y in range(image.height()):
        for x in range(image.width()):
            if image.pixelColor(x, y).alpha() > 0:
                left, right = min(left, x), max(right, x)
                top, bottom = min(top, y), max(bottom, y)
    if right < 0:
        raise SystemExit("The SVG rendered completely empty")

    left = max(0, left - margin)
    top = max(0, top - margin)
    right = min(image.width() - 1, right + margin)
    bottom = min(image.height() - 1, bottom + margin)
    return image.copy(left, top, right - left + 1, bottom - top + 1)


# Generated by GitHub Copilot - Aug-27-2026
def _pack_ico(png_dict: dict[int, bytes]) -> bytes:
    """
    Pack PNG byte streams of multiple sizes into a standard Windows ICO binary.
    """
    header = struct.pack('<HHH', 0, 1, len(png_dict))
    offset = 6 + 16 * len(png_dict)
    entries = []
    data_parts = []
    for size, data in png_dict.items():
        w = 0 if size >= 256 else size
        h = 0 if size >= 256 else size
        entries.append(struct.pack('<BBBBHHII', w, h, 0, 0, 1, 32, len(data), offset))
        data_parts.append(data)
        offset += len(data)
    return header + b''.join(entries) + b''.join(data_parts)


# Generated by GitHub Copilot - Aug-27-2026
def main() -> None:
    """
    Main entry point for rendering all brand assets.
    """
    os.makedirs(RENDERS_DIR, exist_ok=True)
    os.makedirs(GUI_ASSETS_DIR, exist_ok=True)

    app = QGuiApplication.instance() or QGuiApplication(sys.argv[:1])

    # 1. Render light lockup for About dialog (cropped)
    with open(SOURCE_LIGHT, "r", encoding="utf-8") as f:
        light_svg = _resolve_font_stacks(f.read())

    dialog_img = _render_svg_to_image(light_svg, RENDER_WIDTH)
    dialog_cropped = _crop_to_content(dialog_img)
    if not dialog_cropped.save(TARGET_DIALOG_LOCKUP, "PNG"):
        raise SystemExit(f"could not write {TARGET_DIALOG_LOCKUP}")

    with open(TARGET_DIALOG_LOCKUP, "rb") as handle:
        digest = hashlib.sha256(handle.read()).hexdigest()

    print(f"wrote  {TARGET_DIALOG_LOCKUP}")
    print(f"size   {dialog_cropped.width()}x{dialog_cropped.height()}")
    print(f"sha256 {digest}")

    # 2. Render standalone light & dark lockups in mockups/brand/renders/
    light_full = _render_svg_to_image(light_svg, LOCKUP_FULL_WIDTH)
    light_render_path = os.path.join(RENDERS_DIR, "ticketaudit-lockup-light.png")
    light_full.save(light_render_path, "PNG")
    print(f"wrote  {light_render_path}")

    with open(SOURCE_DARK, "r", encoding="utf-8") as f:
        dark_svg = _resolve_font_stacks(f.read())
    dark_full = _render_svg_to_image(dark_svg, LOCKUP_FULL_WIDTH)
    dark_render_path = os.path.join(RENDERS_DIR, "ticketaudit-lockup-dark.png")
    dark_full.save(dark_render_path, "PNG")
    print(f"wrote  {dark_render_path}")

    # 3. Render app icon PNGs at various resolutions
    with open(SOURCE_ICON, "r", encoding="utf-8") as f:
        icon_svg = f.read()

    ico_png_data: dict[int, bytes] = {}
    for size in ICON_SIZES:
        icon_img = _render_svg_to_image(icon_svg, size, size)
        out_png = os.path.join(RENDERS_DIR, f"ticketaudit-app-icon-{size}.png")
        icon_img.save(out_png, "PNG")

        if size in ICO_SIZES:
            ba = QByteArray()
            buf = QBuffer(ba)
            buf.open(QIODevice.OpenModeFlag.WriteOnly)
            icon_img.save(buf, "PNG")
            ico_png_data[size] = bytes(ba)

    print(f"wrote  app icon PNGs for sizes {ICON_SIZES} in {RENDERS_DIR}")

    # 4. Pack multi-size ICO files
    ico_bytes = _pack_ico(ico_png_data)
    with open(TARGET_APP_ICO, "wb") as f:
        f.write(ico_bytes)
    print(f"wrote  {TARGET_APP_ICO} ({len(ico_bytes)} bytes, sizes {ICO_SIZES})")

    with open(TARGET_RENDERS_ICO, "wb") as f:
        f.write(ico_bytes)
    print(f"wrote  {TARGET_RENDERS_ICO}")

    print()
    print("Set _lh in show_about_dialog to that digest, keeping its obfuscation:")
    print(f'    _lh = "x{digest}"[1:]')
    del app


if __name__ == "__main__":
    main()
